# Generated by Django 3.2.5 on 2021-07-21 13:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('root', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='landing.category')),
            ],
        ),
        migrations.CreateModel(
            name='MenuItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, unique=True)),
                ('price', models.IntegerField()),
                ('discount', models.IntegerField(default=0)),
                ('image_name', models.CharField(max_length=100)),
                ('cooking_time', models.TimeField(blank=True, null=True)),
                ('serving_time', models.TimeField(blank=True, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='landing.category')),
            ],
        ),
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capacity', models.IntegerField()),
                ('position_space', models.CharField(max_length=20, unique=True)),
                ('status', models.ForeignKey(blank=True, default=12, null=True, on_delete=django.db.models.deletion.CASCADE, to='landing.table')),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('root', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='landing.status')),
            ],
        ),
        migrations.CreateModel(
            name='Recepites',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_price', models.IntegerField(default=0)),
                ('final_price', models.IntegerField(default=0)),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='landing.status')),
                ('table_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='landing.table')),
            ],
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(default=0)),
                ('time_stamp', models.TimeField()),
                ('menu_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='landing.menuitems')),
                ('recepite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='landing.recepites')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='landing.status')),
            ],
        ),
        migrations.AddField(
            model_name='menuitems',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='landing.status'),
        ),
    ]
